# Personal information
title: rafaelhdr
email: contato@rafaelhdr.com.br
description: >-
  Personal website for rafaelhdr.
  Developer since 15 years old.
  Always learning.
  Likes Linux, DevOps, Python, node.js, Docker and much more.

# URL configuration
baseurl: ""
url: "https://www.rafaelhdr.com.br"

# Social network
twitter_username:       rafaelhdr
github_username:        rafaelhdr
gitlab_username:        rafaelhdr
stackoverflow_username: rafael
stackoverflow_number:   "1543364"
# disqus:
#   shortname: rafaelhdr

# Polyglot
languages: ["en", "pt_br"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true
exclude_from_upload:
  - s3_website.yml
  - README.md
  - Rakefile

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-polyglot
  - jekyll-redirect-from
  - jekyll-sitemap

# Assets
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Sitemap
sitemap:
  filename: "/sitemap.xml"
